### ISSUE TITLE
How to compile for Arduino & use WiFi?

### ISSUE THREAD

**Issue by NicksonYap** [Openhab-Nodes/wakaamaNode#10]
Hi,

I'm new to lwm2m.

I was able to compile and upload using the `pio` command.
Though, I'm not familiar and can't see the Arduino react.

I understand that compile-time definitions are needed, how can we change to source code for it to compile for Arduino?

Even so, I don't see any examples in both Arduino & PlatformIO to select WiFi AP & a server to connect to.

Best Regards,

Nickson

**Comment by davidgraeff** [comment]
An Arduino has no fixed way of entering an IP network (there are several Arduino shields with different network modules). Common ways are via the W5100 and W5500 chip (Ethernet shield and Ethernet shield 2).

This library supports the posix network stack (linux, macOS, windows) and lwip (a lot of embedded sdks and oerating systems), but I haven't written support for those two mentioned chips. 

Your question about WiFi AP is confusing. I'm not aware of a WiFi shield for Arduinos.

**Comment by NicksonYap** [comment]
@davidgraeff I'm sorry I forgot to mention that I was using the ESP8266
