### ISSUE TITLE
Rename to libWakaamaNodes

### ISSUE THREAD

**Issue by davidgraeff** [Openhab-Nodes/wakaamaNode#6]
Rename the library before releasing it.

**Comment by SarenT** [comment]
Hi,

Is the library available in the registry for PlatformIO? I get this error: Error: Library `{'requirements': None, 'name': 'wakaamaNode'}` has not been found in PlatformIO Registry.
with `pio lib install wakaamaNode`

**Comment by davidgraeff** [comment]
The library is prepared to be published but I haven't registered it yet on platformio.
